default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: CodeaTAG_development

test:
  <<: *default
  database: CodeaTAG_test

production:
  <<: *default
  database: CodeaTAG_production
  username: CodeaTAG
  password: <%= ENV['CODEATAG_DATABASE_PASSWORD'] %>
