default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: CodeaNuma_development

test:
  <<: *default
  database: CodeaNuma_test

production:
  <<: *default
  database: CodeaNuma_production
  username: CodeaNuma
  password: <%= ENV['CODEANUMA_DATABASE_PASSWORD'] %>
