# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd32336fe26d31e5a0e05b9fecd7c2ea897707109b2f923d58b0ad37845117944ed32a694f92b0b44a49c122f66a594e643864a37fcdc72ae1ed724ef8d2295
  consumer_key: 	93fRAKGFTq2MqX1d5QGuYjAvA
  consumer_secret: 1lKDGrET23L2N64XwSh2iZOewXSxy4Arik8OogWd7wz5UspcTH
  access_token: 96698334-mtke3YafmhPYn2kMglU5BOGkjCVzm4jXi836Yto1W
  access_token_secret: ilgje4zxdsztTRvhJg9aqf8NYEkFRvlPIpovbXV0OjI6g
  codea_tag_api_token: d4fbea6b599cc35a36b31de388ffdaff

test:
  secret_key_base: b0bef0d2434a36d95a40c77a1511f6846b5c4bfa482804ee09c312f3e0504764614cb02ed8401e159b99ba218ec782670ee8045d1c319b1b4ad52075a9a9333d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["ACCESS_SECRET"] %>


