CONSUMER_KEY: 93fRAKGFTq2MqX1d5QGuYjAvA
CONSUMER_KEY_SECRET: 1lKDGrET23L2N64XwSh2iZOewXSxy4Arik8OogWd7wz5UspcTH
ACCESS_TOKEN: 96698334-mtke3YafmhPYn2kMglU5BOGkjCVzm4jXi836Yto1W
ACCESS_TOKEN_SECRET: ilgje4zxdsztTRvhJg9aqf8NYEkFRvlPIpovbXV0OjI6g
CODEA_TAG_API_TOKEN: d4fbea6b599cc35a36b31de388ffdaff